
version: '3.8'

services:
  postgres_nlw:
    container_name: postgres_nestjs
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api-nestjs